# Generated by Django 5.1.1 on 2024-09-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
